### ISSUE TITLE
404 Not Found results for www.phpflickr.com

### ISSUE THREAD

**Issue by SleeplessinDC** [dan-coulter/phpflickr#40]
In the Readme and elsewhere, all links that point to phpflickr.com give a 404 Not Found response. For example: http://www.phpflickr.com/  I tried https://www.phpflickr.com/ but didn't work either.

![not_found_for_phpflickr](https://cloud.githubusercontent.com/assets/2455734/4030642/64a08c48-2c5f-11e4-88d0-3cbd2e3e8d6c.png)

**Comment by metrolibrary** [comment]
Did you ever find a solution for this?  I'm having the same issue.

**Comment by fergbrain** [comment]
Works for me
