### ISSUE TITLE
phpFlickr failing with "#98 - Invalid auth token"

### ISSUE THREAD

**Issue by igneosaur** [dan-coulter/phpflickr#48]
This is an umbrella issue for all "Invalid auth token" issues and maybe even some other issues reporting that phpFlickr is failing recently (https://github.com/dan-coulter/phpflickr/issues/36, https://github.com/dan-coulter/phpflickr/issues/41, https://github.com/dan-coulter/phpflickr/issues/25, https://github.com/dan-coulter/phpflickr/issues/23).

This problem affects applications that have been using phpFlickr since before 26th May 2014 and have updated the submodule to find breakages with "Invalid auth token"s and other breaking changes to the structure of data coming back from Flickr.

To fix, uncomment [this line](https://github.com/dan-coulter/phpflickr/blob/master/phpFlickr.php#L313) and then comment out the line above.

**Comment by maan81** [comment]
I had to add 
```
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
```
in master branch to handle the invalid token issue. Its not there in mater branch.
