### ISSUE TITLE
Get the url for the photo after upload

### ISSUE THREAD

**Issue by matiasfha** [dan-coulter/phpflickr#51]
I'm using sync_upload.. would be nice if the method also return the url for the photo and not just the ID.. i need to embed the photo in the website..

**Comment by marceloj** [comment]
$result = $flickr->sync_upload($File,$Title, $Description,
 $Tags,$is_public,$is_friend,$is_family);//1,1,1,1,2,1,2

if(isset($result))
	echo '<a href=https://www.flickr.com/photos/'.IDUSER.'/' .$result. '> Link</a>';
