### ISSUE TITLE
http://phpflickr.com/tools/auth/ broken?

### ISSUE THREAD

**Issue by metrolibrary** [dan-coulter/phpflickr#53]
Hi there!  I'm trying to set up a token to view private photos through our Drupal site.  When I visit this page, it's broken.  Do you have another link that one to use to generate a token?

Thanks!

**Comment by glenn-nz** [comment]
For me too, where can we find the auth tool?

**Comment by jrtilson** [comment]
For anyone looking for the old tool, I've forked this repo and included the code here: https://github.com/jrtilson/phpflickr/tree/master/token

**Comment by sebastienbarre** [comment]
Thanks. It's too bad it's gone, it was a good way to get a token without having to setup your own server.
