### ISSUE TITLE
Invalid signature on sync_upload

### ISSUE THREAD

**Issue by 3m0** [dan-coulter/phpflickr#54]
Hello, I've created a testing account on flickr and set up an application in the API garden and gave it delete permissions. However, when I try to upload any photos, I get an error saying that the signature is invalid. I already checked my keys and secrets and everything is right. I don't know what could be happening. Did something change in the API? I can provide any information you want, even my secrets, since it's a testing account.

**Comment by locvfx** [comment]
You might post error reports from web server so that the world can help you.

**Comment by iwiktor** [comment]
If you use php >=5.5, you should try update the sync_file function with this fix.

//$args['photo'] = '@' . $photo;
$args['photo'] = new CURLFile($photo);

File uploading has been changed in PHP5.5, so CURL sends the @string not the binary file to Flickr, so the calculated sign is broken.

More info: http://php.net/manual/en/class.curlfile.php

**Comment by joezine** [comment]
@wikt0r  hi,  I changed code the code. But images don't be uploaded. Any idea?

**Comment by ayrtoncz** [comment]
I get this error on "sync_upload" and this fix didn't help, still getting the same error. I'm on PHP 5.6

**Comment by samwilson** [comment]
If you want to try a different package, I've forked this one and am attempting to fix some problems; see https://github.com/samwilson/phpflickr — I think uploading is working.
