### ISSUE TITLE
Help using this wrapper.

### ISSUE THREAD

**Issue by JoabMendes** [dan-coulter/phpflickr#65]
I could read the code and try to find a way to do what I want, but probably someone have already done what I am looking for. I am building a new version of an website where its galleries will be connected with a flickr account. The problem is: I have to get all the pictures that are stored in the old website and create galleries with these pics. The procedure would be:

**Get the gallery title from the database `>` Create a flicker gallery with this title `>` get the id and add pictures from the database to the new created flickr gallery.**

Could someone help me how to do that using this wrapper? I tried to find an example but I couldn't find any.

**Comment by gegere** [comment]
I think I could help you, leaving the office now but please send me an email and I will send you examples using this library.

**Comment by JoabMendes** [comment]
I used the API directly.
