### ISSUE TITLE
Can't access API..

### ISSUE THREAD

**Issue by bostonmacosx** [dan-coulter/phpflickr#67]
I have a valid key and called 

`$f = new \AAC\Classes\phpFlickr(getenv('FLICKRAPP'));
 $recent = $f->photosets_getList();
`

recent is always coming back as false though. 

not sure what I'm going wrong as the troublehooting is minimal.

**Comment by bostonmacosx** [comment]
I'm now having a infintie loop issue with the getToken page...

**Comment by sookoll** [comment]
Hi, I struggled same problem, got it work with this fix:
https://github.com/sookoll/phpflickr/blob/master/getToken.php
