### ISSUE TITLE
Can't upload photo: The Flickr API returned the following error: #96 - Invalid signature

### ISSUE THREAD

**Issue by HubertG97** [dan-coulter/phpflickr#68]
I can't upload a photo because of the following error: The Flickr API returned the following error: #96 - Invalid signature

**Comment by zaib32** [comment]
I'm having the same problem. Now after wasting my time I just come to knwo that this lib is using some old APIs which are deprecated.

**Comment by Harutsardaryan1** [comment]
Hi, did anyone fixed this issue?
