### ISSUE TITLE
Anyone maintaining this?

### ISSUE THREAD

**Issue by samwilson** [dan-coulter/phpflickr#74]
@dan-coulter it looks like you're not maintaining this any more. Is that correct? (No worries of course! I don't mean to imply that you should be.)

@ everyone else: is anyone maintaining a current fork of this? There looks to be lots of useful PRs and issues.

:-)

**Comment by samwilson** [comment]
@zgetro you are perhaps the leading forker? :) Yours is the most-downloaded fork on Packagist.

**Comment by clintonb** [comment]
It seems all @zgetro did was add a `compose.json` file. The Flickr API code is unchanged.

**Comment by samwilson** [comment]
Yes, true. But maybe that means they're willing to become a maintainer? @clintonb which codebase are you running?

**Comment by clintonb** [comment]
I'm still using a downloaded version from 2012! I'm just returning to a mostly-untouched Wordpress plugin that I want to make PHP7-compatible.

**Comment by samwilson** [comment]
I've started merging a few of the PRs to my [fork](https://github.com/samwilson/phpflickr).

**Comment by joezine** [comment]
@samwilson  I have used composer. But it showed below. Please advice 

`composer require samwilson/phpflickr


  [InvalidArgumentException]
  Could not find package samwilson/phpflickr at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]..composer require samwilson/phpflickr


  [InvalidArgumentException]
  Could not find package samwilson/phpflickr at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]..`

**Comment by samwilson** [comment]
@joezine I'm afraid I'm now using https://github.com/TheFox/flickr-cli

**Comment by samwilson** [comment]
I need phpFlickr again for another thing I'm working on, so I've forked it to [samwilson/phpflickr](https://packagist.org/packages/samwilson/phpflickr) and will do my best to maintain it and respond to bug reports and feature requests.
