### ISSUE TITLE
Struggling to authenticate

### ISSUE THREAD

**Issue by carlos-mg89** [dan-coulter/phpflickr#88]
Hi!

It seems this repository is maintained (because of recent commits), so I'll go ahead with my question.

I'm having troubles to authenticate, so I can perform requests that require write permissions. I just want to automate some tasks, performed by my user, instead of having to do them manually. Basically, I need to upload pictures.

To do so, I thought I could do it without having to perform an authentication, with my api secret and key. But it doesn't seem to be the case.

I tried this:

```
$flickrService = new PhpFlickr(
            $this->getParameter("flickr_key"),
            $this->getParameter("flickr_secret"),
        );

$uploadPhotoResponse = $flickrService->sync_upload(
            $uploadedFile->getPath() . "/" . $uploadedFile->getFilename(),
            $title,
            $description,
            $tags,
            false
        );
```

However it returns the following (I've created this JSON only for simplification purposes:

```
array:4 [▼
  "success" => "KO"
  "error_msg" => "Invalid signature"
  "error_code" => "96"
  "response" => """
    <?xml version="1.0" encoding="utf-8" ?>
    <rsp stat="fail">
    \t<err code="96" msg="Invalid signature" />
    </rsp>
    """
]
```

The code to generate the above JSON was:

```
[
            "success" => $uploadPhotoResponse ? "OK" : "KO",
            "error_msg" => $flickrService->error_msg,
            "error_code" => $flickrService->error_code,
            "response" => $flickrService->response,
        ]
```

So I tried to authenticate before posting the picture (after following the instructions of the auth.php file):

```
unset($_SESSION['phpFlickr_auth_token']);
$authResponse = $flickrService->auth("write", false); // I've tried setting to true the second parameter
```

What happens after I try to run the above code, is that I get redirected to Flickr website. And I'm simply told "PERMISSION DENIED".

The URL has the following pattern: `https://www.flickr.com/services/auth/?api_key=MY_API_KEY&perms=read&api_sig=REQUEST_SIGNATURE`

I've read something in the auth.php about "frob", but I don't understand what's it.

Could anyone help me please? I only need some guidance, I can deal with the rest.

Thanks in advance!

**Comment by carlos-mg89** [comment]
Nevermind, it seems like the Flickr API deprecated every non OAuth access: https://www.flickr.com/services/api/auth.oauth.html#request_token

Thanks anyway! This client still works when there's no need to authenticate. Tested to obtain photos data.

Cheers

**Comment by dan-coulter** [comment]
@carlos-mg89 you might try this fork that is more up to date: https://github.com/samwilson/phpflickr

**Comment by carlos-mg89** [comment]
Thanks a lot @dan-coulter ! That library is really up-to-date and works like a charm. Even for uploading pictures!
